In [7]:
import pandas as pd

In [8]:
df = pd.read_csv("IMDB Dataset.csv")
df.head()

                                              review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

In [9]:
df.shape

(50000, 2)

In [10]:
df.isna().sum()

review       0
sentiment    0
dtype: int64

In [11]:
df.drop_duplicates(inplace=True)

In [12]:
df.shape

(49582, 2)

### Pre-processing

In [13]:
# Converting to Lowercase

df["review"] = df["review"].str.lower()

In [14]:
# Removing the URLs

import re

def remove_urls(text):
    text = re.sub(r"http\S+", "", text) # (pattern, replacement, string) ex - https://www.google.com
    return text

df["review"] = df["review"].apply(remove_urls)

In [15]:
# Removing Punctuations

def remove_punctuation(text):
    text = re.sub(r"[^A-Za-z0-9\s]", "", text) # A-Z, a-z, 0-9  \s
    return text

df["review"] = df["review"].apply(remove_punctuation)

In [16]:
# Removing HTML tags

def remove_html_tags(text):
    text = re.sub(r"<.*?>", "", text) # HTML Tags
    return text

df["review"] = df["review"].apply(remove_html_tags)

In [17]:
# removing the stopwords

#import nltk

#nltk.download("punkt")
#nltk.download("punkt_tab")
#nltk.download("stopwords")

In [18]:
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords

In [19]:
#example

sample_text = "I like coding in Py"
tokens = word_tokenize(sample_text)
tokens

['I', 'like', 'coding', 'in', 'Py']

In [22]:
def remove_stopwords(text):
    tokens = word_tokenize(text)
    stop_words = stopwords.words("english")
    
    for word in tokens:
        if word in stop_words:
            text.replace(word, "")
            
    return text

df["review"] = df["review"].apply(remove_stopwords)

In [25]:
df["review"] = df["review"].apply(remove_stopwords)

In [26]:
df.head()

,review,sentiment,removes
0,one of the other reviewers has mentioned that ...,positive,one of the other reviewers has mentioned that ...
1,a wonderful little production br br the filmin...,positive,a wonderful little production br br the filmin...
2,i thought this was a wonderful way to spend ti...,positive,i thought this was a wonderful way to spend ti...
3,basically theres a family where a little boy j...,negative,basically theres a family where a little boy j...
4,petter matteis love in the time of money is a ...,positive,petter matteis love in the time of money is a ...

In [27]:
df.drop("removes", axis=1, inplace=True)

In [28]:
df.head()

                                              review sentiment
0  one of the other reviewers has mentioned that ...  positive
1  a wonderful little production br br the filmin...  positive
2  i thought this was a wonderful way to spend ti...  positive
3  basically theres a family where a little boy j...  negative
4  petter matteis love in the time of money is a ...  positive

In [32]:
# stemming 
# played -> play
# running -> run


# PorterStemming

from nltk.stem import PorterStemmer

def stemming(text):
    ps = PorterStemmer()
    stemmed_words = []
    
    tokens = word_tokenize(text)
    for token in tokens:
        stemmed_token = ps.stem(token)
        stemmed_words.append(stemmed_token)
        
    return " ".join(stemmed_words)

df["review"] = df["review"].apply(stemming)

In [33]:
df.head()

                                              review sentiment
0  one of the other review ha mention that after ...  positive
1  a wonder littl product br br the film techniqu...  positive
2  i thought thi wa a wonder way to spend time on...  positive
3  basic there a famili where a littl boy jake th...  negative
4  petter mattei love in the time of money is a v...  positive

In [ ]:
# Encoding

from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

df["sentiment"] = le.fit_transform(df["sentiment"]) # Positive => 1, negative => 0

In [36]:
y = df["sentiment"]
y

0        1
1        1
2        1
3        0
4        1
        ..
49995    1
49996    0
49997    0
49998    0
49999    0
Name: sentiment, Length: 49582, dtype: int64

In [ ]:
# vectorization